purpose_rename <- c(
  "wish_purp_work" = "Work",
  "wish_purp_school" = "School",
  "wish_purp_childcare" = "Childcare",
  "wish_purp_shopping" = "Shopping",
  "wish_purp_fun" = "Fun, social, recreation",
  "wish_purp_special" = "Special events",
  "wish_purp_airport" = "Airport",
  "wish_purp_medical" = "Medical",
  "wish_purp_social" = "Social services",
  "wish_purp_judicial" = "Judicial services")


barrier_rename <-c("barrier_toolong" = "Takes too long",
                   "barrier_noflex" = "Not flexible enough",
                   "barrier_notfreq" = "Not frequent enough",
                   "barrier_nostophome" = "No stop close to home",
                   "barrier_nostopdest" = "Not stop close to dest. ",
                   "barrier_transfer" = "Too many transfers",
                   "barrier_safeothers" = "Safety concerns, others behavior",
                   "barrier_safedrive" = "Safety concerns, operation",
                   "barrier_notearly" = "Does not run early enough",
                   "barrier_ontime" = "Does not arrive on time",
                   "barrier_knowhow" = "Don't know how to use",
                   "barrier_cost" = "Too expensive",
                   "barrier_nottried" = "Haven't tried yet",
                   "barrier_other" = "Other" ,
                   "barrier_health" = "Health concerns",
                   "barrier_notlate" = "Doesn't run late enough")


accessbarrier_rename <-c("accessbarrier_bikeparking" = "More bike parking",
                         "accessbarrier_improvebikelane" = "Better bikes lines",
                         "accessbarrier_lighting" = "More lighting",
                         "accessbarrier_newsidewalk" = "New sidewalks or crosswalks",
                         "accessbarrier_other" = "Other",
                         "accessbarrier_parking" = "More parking",
                         "accessbarrier_flexservice" = "Flexible, on-demand service",
                         "accessbarrier_improvesidewalk" = "Improved sidewalks and crosswalks",
                         "accessbarrier_newbikelanes" = "New bikes lanes",
                         "accessbarrier_nothing" = "Nothing",
                         "accessbarrier_othersafety" = "Other safety improvements",
                         "accessbarrier_scootershare" = "Scooter/bike share access")


satisfaction_rename<-c("sat_safebusday"= "Safety onboard, day",
                       "sat_safewaitday"= "Safety waiting, day",
                       "sat_safebusnight"= "Safety onboard, night",
                       "sat_safewaitnight"= "Safety waiting, night",
                       "sat_safeflm"= "Safety: getting to/from transit",
                       "sat_cleanstop"= "Cleanliness, stops",
                       "sat_cleanbus"= "Cleanliness, onboard",
                       "sat_freq_serv" = "Service frequency",
                       "sat_bus" = "Metro Bus overall",
                       "sat_ontime" = "Ontime perf.",
                       "sat_traveltime" = "Travel time",
                       "sat_comf" = "Comfort of bus",
                       "sat_seatbus" = "Seating: onboard",
                       "sat_seatstop" = "Seating: stop",
                       "sat_transitwait" = "Transfer wait time",
                       "sat_driver" = "Drivers' operation",
                       "sat_plantool" = "Trip plan: overall",
                       "sat_plantoolease" = "Trip plan: ease of use",
                       "sat_plantoolinfo" = "Trip plan: accurate info",
                       "sat_plantooltime" = "Trip plan: accurate timing",
                       "sat_plantoolmode" = "Trip plan: multimodal",
                       "sat_safe_flm" = "Safety: getting to/from transit",
                       "sat_ontime_stop" = "Ontime perf.: to stop",
                       "sat_ontime_dest" = "Ontime perf.: to destination",
                       "sat_orca" = "ORCA payment: overall",
                       "sat_orcaload" = "ORCA payment: loading value",
                       "sat_infoplanned" = "Info: planned changes",
                       "sat_infounplanned" = "Info: unplanned changes",
                       "sat_overall" = "Overall")

